# Mandatory
server:
  port: 5002

# Mandatory.
cache:
  host: "0.0.0.0"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 0

# Optional.
responseCache:
  mongoURL: "mongodb://tvast:password@0.0.0.0:27017/ps?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  synchronous:
    mongoURL: "mongodb://tvast:password@0.0.0.0:27017/ps?authSource=admin"

  #webhook:
  #  url: "https://beckn.free.beeceptor.com/clientURL"

  #messageQueue:
  #  amqpURL: "amqp://guest:guest@localhost:5672"
  #  incomingQueue: "protocol-server-incoming"
  #  outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bap

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "inbox"
    outboxQueue: "outbox"
    amqpURL: "amqp://tvast:password@0.0.0.0:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl : "PT15S"
      init:
        ttl : "PT15S"
      select:
        ttl : "PT15S"
      confirm:
        ttl : "PT15S"
      status:
        ttl : "PT15S"
      track:
        ttl : "PT15S"
      cancel:
        ttl : "PT15S"
      update:
        ttl : "PT15S"
      rating:
        ttl : "PT15S"
      support:
        ttl : "PT15S"
      get_cancellation_reasons:
        ttl : "PT15S"
      get_rating_categories:
        ttl : "PT15S"
      cancellation:
        ttl : "PT15S"

    responses: 
      on_search:
        ttl: "PT15S"
      on_init:
        ttl: "PT15S"
      on_select:
        ttl: "PT15S"
      on_confirm:
        ttl: "PT15S"
      on_status:
        ttl: "PT15S"
      on_track:
        ttl: "PT15S"
      on_cancel:
        ttl: "PT15S"
      on_update:
        ttl: "PT15S"
      on_rating:
        ttl: "PT15S"
      on_support:
        ttl: "PT15S"
      cancellation_reasons:
        ttl: "PT15S"
      rating_categories:
        ttl: "PT15S"          
  
  # Mandatory.
  privateKey: "PRIVATE_KEY"
  publicKey: "PUBLIC_KEY"

  # Mandatory.
  subscriberId: "BAP_SUBSCRIBER_ID"
  subscriberUri: "BAP_SUBSCRIBER_URL"

  # Mandatory.
  registryUrl: REGISTRY_URL
  auth: false
  uniqueKey: "BAP_SUBSCRIBER_ID_KEY"
  
  # Mandatory.
  city: "*"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2

  telemetry:
    network:
      url: ""
    raw:
      url: ""  
    batchSize: 100
    # In minutes
    syncInterval: 1
    # Either can be LOCAL or REDIS
    storageType: "LOCAL"
    backupFilePath: "backups"
    redis:
      db: 4
  service: 
    name: "bap_network_service"
    version: "1.0.0"
